spec:
  rules:
    - host: api.devops-ninja.ml
      http:
        paths:
          - path: /book
            backend:
              serviceName: api-book
              servicePort: 80
          - path: /song
            backend:
              serviceName: api-song
              servicePort: 80
          - path: /video
            backend:
              serviceName: api-video
              servicePort: 80